SELECT * FROM USER_TABLES;
SELECT * FROM SALE_ITEMS_BK;

SELECT * FROM SALE_ITEMS;
SELECT * FROM SALES;
SELECT * FROM ITEMS;
SELECT * FROM CUSTOMERS;
SELECT * FROM EMPLOYEES;
SELECT * FROM ALL_CUSTOMERS;

DROP FUNCTION GET_SUCURSALCUSTOMER;
