DROP TABLE USERS CASCADE CONSTRAINTS;
CREATE TABLE USERS(
    USR_ID NUMBER PRIMARY KEY,
    USR_NAME VARCHAR2(60) NOT NULL,
    USR_NICKNAME VARCHAR2(30) NOT NULL,
    USR_EMAIL VARCHAR2(40) NOT NULL UNIQUE,
    USR_PASSWORD VARCHAR2(30) NOT NULL,
    PRIV_ID NUMBER
);

DROP TABLE USR_PRIVILEGES;
CREATE TABLE USR_PRIVILEGES(
    PRIV_ID NUMBER PRIMARY KEY,
    PRIV_KEY VARCHAR2(10) NOT NULL,
    PRIV_DESC VARCHAR2(100) NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT FK_USRS_PRIVID FOREIGN KEY (PRIV_ID) REFERENCES USR_PRIVILEGES(PRIV_ID);

--------@CHECHESWAP------------------------------------@CHECHESWAP--------------------------------@CHECHESWAP------------------------------@CHECHESWAP------------------------------------@CHECHESWAP--------------------------------@CHECHESWAP----------------------

DROP SEQUENCE SEQ_USRS_AI;
CREATE SEQUENCE SEQ_USRS_AI START WITH 1;
CREATE OR REPLACE TRIGGER TRIG_USRS_AI BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT SEQ_USRS_AI.NEXTVAL INTO :NEW.USR_ID FROM DUAL;
END;

DROP SEQUENCE SEQ_USRPRIVGS_AI;
CREATE SEQUENCE SEQ_USRPRIVGS_AI START WITH 1;
CREATE OR REPLACE TRIGGER TRIG_USRPRIVGS_AI BEFORE INSERT ON USR_PRIVILEGES
FOR EACH ROW
BEGIN
    SELECT SEQ_USRPRIVGS_AI.NEXTVAL INTO :NEW.PRIV_ID FROM DUAL;
END;

--------@CHECHESWAP------------------------------------@CHECHESWAP--------------------------------@CHECHESWAP------------------------------@CHECHESWAP------------------------------------@CHECHESWAP--------------------------------@CHECHESWAP----------------------

INSERT INTO USR_PRIVILEGES(PRIV_KEY, PRIV_DESC) VALUES('SUPER_USER','TODOS LOS PRIVILEGIOS DE OPERACION');
INSERT INTO USR_PRIVILEGES(PRIV_KEY, PRIV_DESC) VALUES('MIDLE_USER','SOLO LECTURA');

INSERT INTO USERS(USR_NAME, USR_NICKNAME, USR_EMAIL, USR_PASSWORD, PRIV_ID) VALUES('JESUS NAVARRETE','CHECHESWAP','A301429@UACH.MX','123',1);
INSERT INTO USERS(USR_NAME, USR_NICKNAME, USR_EMAIL, USR_PASSWORD, PRIV_ID) VALUES('RAMON SICHER','SICHER','A301485@UACH.MX','123',2);
INSERT INTO USERS(USR_NAME, USR_NICKNAME, USR_EMAIL, USR_PASSWORD, PRIV_ID) VALUES('ADMIN','ADMIN','A41354@UACH.MX','ADMIN',2);
COMMIT;




